# Generated by Django 4.0.2 on 2022-08-04 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gtotd_gtotdcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtotdcomment',
            name='gtotd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gtotd'),
        ),
    ]
