# Generated by Django 4.0.2 on 2022-08-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_gtotdcomment_gtotd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gtotd',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='gtotdcomment',
            old_name='user',
            new_name='user_id',
        ),
    ]
