# Generated by Django 4.0.2 on 2022-08-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_user_gtotd_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gtotd',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='gtotdcomment',
            old_name='user_id',
            new_name='user',
        ),
    ]
